[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
polymarket_paper = "AmuwGa8LXKW63ZHzGm1TkqSugbJ8fMVXr6HKksYkwUNT"

[programs."https://rpc.magicblock.app/devnet/"]
polymarket_paper = "J7AUjePzLNxCVc2rgDkp2P5xbwzaegEJyThB56QhH65F"

[programs.localnet]
polymarket_paper = "Azr9LDo9RCEFMzKoC5SA1yeJffD2tyDvnuMyUSFkRT6P"

[programs.mainnet]
polymarket_paper = "ACiKbUuELDHuVfoaSsZy9EcvPEqktrgxH9VfVEbqnqwU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.magicblock.app/devnet/"
wallet = "~/.config/solana/phantom.json"

[scripts]
initialise = "ts-node tests/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
